Repository BirbJS/Birb, pull requests merged in 2021-12, with the labels that each got.

#16 update: add role methods, improve role handling & reordering
  src/classes/Cache.ts
  src/classes/Client.ts
  src/classes/ClientUser.ts
  src/classes/Permissions.ts
  src/classes/Role.ts
  src/classes/blocks/BitsBlock.ts
  src/classes/blocks/GuildBlock.ts
  src/classes/blocks/PermissionsBlock.ts
  src/classes/blocks/RolePermissionsBlock.ts
  src/classes/http/Request.ts
  src/classes/websocket/Websocket.ts
  src/classes/websocket/handlers/GUILD_ROLE_UPDATE.ts
  src/constants/Status.ts
  src/index.ts
  src/util/Addons.ts
  src/util/Pair.ts
Labels: enhancement, v1

#18 some cool changes
  .DS_Store
  src/classes/Client.ts
  src/classes/GuildChannel.ts
  src/classes/Message.ts
  src/classes/User.ts
  src/util/Constants.ts
  test.js
Labels: enhancement, v1

#21 update: improve logging, debug and devtools
  .gitignore
  package-lock.json
  package.json
  src/classes/Client.ts
  src/classes/http/Request.ts
  src/classes/websocket/Websocket.ts
Labels: enhancement, v1

#23 feat: Add property `system`, `type` in Message
  package-lock.json
  src/classes/Message.ts
  src/util/Constants.ts
Labels: enhancement, awaiting approval, v1

#29 update: some things
  .gitignore
  package-lock.json
  package.json
  typedoc.json
Labels: enhancement, v1

#30 fix: accentColor issue
  src/classes/ClientUser.ts
Labels: bug, v1

#32 fix(exports): Export new constants
  src/index.ts
Labels: enhancement, v1

#33 fix: inability to resume connections
  package-lock.json
  src/classes/websocket/Websocket.ts
  src/classes/websocket/handlers/RESUMED.ts
Labels: bug, v1

#34 docs: add all tsdoc comments
  package-lock.json
  package.json
  src/classes/BaseUser.ts
  src/classes/Channel.ts
  src/classes/Client.ts
  src/classes/ClientUser.ts
  src/classes/Guild.ts
  src/classes/GuildChannel.ts
  src/classes/GuildMember.ts
  src/classes/Intents.ts
  src/classes/Message.ts
  src/classes/PartialUser.ts
  src/classes/PermissionOverwrite.ts
  src/classes/Permissions.ts
  src/classes/Role.ts
  src/classes/RolePermissionOverwrite.ts
  src/classes/TextBasedChannel.ts
  src/classes/TextChannel.ts
  src/classes/ThreadChannel.ts
  src/classes/User.ts
  src/classes/UserPermissionOverwrite.ts
  src/classes/blocks/BitsBlock.ts
  src/classes/blocks/CachedBlock.ts
  src/classes/blocks/ChannelBlock.ts
  src/classes/blocks/ChannelPermissionsBlock.ts
  src/classes/blocks/GuildBlock.ts
  src/classes/blocks/GuildChannelBlock.ts
  src/classes/blocks/GuildMemberBlock.ts
  src/classes/blocks/GuildMemberRoleBlock.ts
  src/classes/blocks/MessageBlock.ts
  src/classes/blocks/PermissionsBlock.ts
  src/classes/blocks/RoleBlock.ts
  src/classes/blocks/RolePermissionsBlock.ts
  src/classes/blocks/UserBlock.ts
  src/classes/cache/CCache.ts
  src/classes/cache/CGCache.ts
  src/classes/cache/Cache.ts
  src/classes/cache/RefrenceCache.ts
  src/classes/message/MessageAttachment.ts
  src/classes/message/embed/EmbedAuthor.ts
  src/classes/message/embed/EmbedField.ts
  src/classes/message/embed/EmbedFooter.ts
  src/classes/message/embed/EmbedMedia.ts
  src/classes/message/embed/MessageEmbed.ts
  src/classes/websocket/InternalWebsocket.ts
  src/classes/websocket/Websocket.ts
  src/util/Constants.ts
  src/util/Pair.ts
  typedoc.json
Labels: documentation, v1

#35 fix(Types): Fix typings
  package-lock.json
  package.json
  src/classes/Message.ts
  src/classes/message/embed/EmbedAuthor.ts
  src/classes/message/embed/EmbedChild.ts
  src/classes/message/embed/EmbedFooter.ts
  src/classes/message/embed/EmbedMedia.ts
  src/classes/message/embed/MessageEmbed.ts
  src/util/Types.ts
Labels: bug, work in progress, v1
